services:
  tx-pipe-btc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BLOCKCHAIN_NAME: "btc"
      secrets:
        - dotenv
    image: tx-pipe:btc
    env_file:
      - .env

secrets:
  dotenv:
    file: .env
