services:
  tx-pipe-btc:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        INSTALL_DEV: "false"
        BLOCKCHAIN_NAME: "btc"
    image: tx-pipe:btc
    env_file:
      - .env
