services:
  tx-pipe-btc:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BLOCKCHAIN_NAME: "btc"
      secrets:
        - dotenv
    image: tx-pipe:btc-latest
    env_file:
      - .env

secrets:
  dotenv:
    file: .env.build
